baseURL = 'https://www.magictomato.ch/'
languageCode = 'fr-CH'
title = 'MagicTomato'
disableKinds = ['taxonomy', 'term', 'section']
enableRobotsTXT = true

[params]
    Description = "TODO"
    Keywords = ["TODO"]

[build]
    [build.buildStats]
        enable = true
    [[build.cachebusters]]
        source = 'assets/notwatching/hugo_stats\.json'
        target = 'css'
    [[build.cachebusters]]
        source = '(postcss|tailwind)\.config\.js'
        target = 'css'
[module]
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.mounts]]
        disableWatch = true
        source = 'hugo_stats.json'
        target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'